"""Add DivisionMembership model for division heads

Revision ID: 1a318241ac06
Revises: 831257aa85be
Create Date: 2026-02-18 13:53:50.466116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a318241ac06'
down_revision = '831257aa85be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('event_cycle_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('is_division_head', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], name='fk_division_memberships_division_id'),
    sa.ForeignKeyConstraint(['event_cycle_id'], ['event_cycles.id'], name='fk_division_memberships_event_cycle_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_division_memberships_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'division_id', 'event_cycle_id', name='uq_division_membership_user_div_cycle')
    )
    with op.batch_alter_table('division_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_division_memberships_division_id'), ['division_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_division_memberships_event_cycle_id'), ['event_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_division_memberships_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('division_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_division_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_division_memberships_event_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_division_memberships_division_id'))

    op.drop_table('division_memberships')
    # ### end Alembic commands ###
