"""Add income fields to work items

Revision ID: 66a9f637a173
Revises: n4o5p6q7r8s9
Create Date: 2026-03-24 16:08:59.572109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a9f637a173'
down_revision = 'n4o5p6q7r8s9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('income_estimate_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('income_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_column('income_notes')
        batch_op.drop_column('income_estimate_cents')

    # ### end Alembic commands ###
