"""Add key dates to event_cycles

Revision ID: 774f10adfdeb
Revises: 7bc8eae7ae02
Create Date: 2026-02-19 23:16:42.666493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774f10adfdeb'
down_revision = '7bc8eae7ae02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('submission_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('approval_target_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('finalization_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_cycles', schema=None) as batch_op:
        batch_op.drop_column('finalization_date')
        batch_op.drop_column('approval_target_date')
        batch_op.drop_column('submission_deadline')
        batch_op.drop_column('event_start_date')

    # ### end Alembic commands ###
