"""Add quickbooks_account_name to expense_accounts

Revision ID: 7bc8eae7ae02
Revises: 1a318241ac06
Create Date: 2026-02-19 20:57:30.601967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc8eae7ae02'
down_revision = '1a318241ac06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quickbooks_account_name', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_accounts', schema=None) as batch_op:
        batch_op.drop_column('quickbooks_account_name')

    # ### end Alembic commands ###
