"""empty message

Revision ID: 7e94620bf16a
Revises: 
Create Date: 2026-01-21 14:22:16.867771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e94620bf16a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('request_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('revision_note', sa.Text(), nullable=True),
    sa.Column('status_at_submission', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'revision_number', name='uq_request_revision_number')
    )
    with op.batch_alter_table('request_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_revisions_request_id'), ['request_id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('event_cycle', sa.String(length=64), nullable=False),
    sa.Column('requesting_department', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_status', sa.String(length=32), nullable=False),
    sa.Column('kickback_reason', sa.Text(), nullable=True),
    sa.Column('current_revision_id', sa.Integer(), nullable=True),
    sa.Column('approved_revision_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('final_approval_note', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_revision_id'], ['request_revisions.id'], ),
    sa.ForeignKeyConstraint(['current_revision_id'], ['request_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('item_description', sa.Text(), nullable=True),
    sa.Column('spend_type', sa.String(length=64), nullable=False),
    sa.Column('spend_group', sa.String(length=64), nullable=True),
    sa.Column('approval_group_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.id'], name='fk_budget_item_types_approval_group_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    with op.batch_alter_table('budget_item_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_item_types_approval_group_id'), ['approval_group_id'], unique=False)

    op.create_table('request_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='fk_request_audit_request_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_audit_events_request_id'), ['request_id'], unique=False)

    op.create_table('request_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='fk_request_comments_request_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_comments_request_id'), ['request_id'], unique=False)

    op.create_table('request_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name='fk_request_drafts_request_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_drafts_request_id'), ['request_id'], unique=True)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('approval_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.id'], name='fk_user_roles_approval_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_roles_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_code', name='uq_user_role_once')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_approval_group_id'), ['approval_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_code'), ['role_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    op.create_table('draft_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=True),
    sa.Column('budget_item_type_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['budget_item_type_id'], ['budget_item_types.id'], name='fk_draft_lines_budget_item_type_id'),
    sa.ForeignKeyConstraint(['draft_id'], ['request_drafts.id'], name='fk_draft_lines_draft_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_lines_budget_item_type_id'), ['budget_item_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_lines_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_lines_sort_order'), ['sort_order'], unique=False)

    op.create_table('request_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('budget_item_type_id', sa.Integer(), nullable=True),
    sa.Column('requester_comment', sa.Text(), nullable=True),
    sa.Column('public_line_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['budget_item_type_id'], ['budget_item_types.id'], name='fk_request_lines_budget_item_type_id'),
    sa.ForeignKeyConstraint(['revision_id'], ['request_revisions.id'], name='fk_request_lines_revision_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id', 'public_line_number', name='uq_revision_public_line_number')
    )
    with op.batch_alter_table('request_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_lines_budget_item_type_id'), ['budget_item_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_lines_public_line_number'), ['public_line_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_lines_revision_id'), ['revision_id'], unique=False)

    op.create_table('line_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_line_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_line_id'], ['request_lines.id'], name='fk_line_audit_request_line_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_audit_events_request_line_id'), ['request_line_id'], unique=False)

    op.create_table('line_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_line_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['request_line_id'], ['request_lines.id'], name='fk_line_comments_request_line_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_comments_request_line_id'), ['request_line_id'], unique=False)

    op.create_table('line_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_line_id', sa.Integer(), nullable=False),
    sa.Column('approval_group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('internal_admin_note', sa.Text(), nullable=True),
    sa.Column('external_admin_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('final_decision_note', sa.Text(), nullable=True),
    sa.Column('final_decision_at', sa.DateTime(), nullable=True),
    sa.Column('final_decision_by_user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.id'], name='fk_line_reviews_approval_group_id'),
    sa.ForeignKeyConstraint(['request_line_id'], ['request_lines.id'], name='fk_line_reviews_request_line_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_line_id', 'approval_group_id', name='uq_line_review_once')
    )
    with op.batch_alter_table('line_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_reviews_approval_group_id'), ['approval_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_reviews_request_line_id'), ['request_line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_reviews_request_line_id'))
        batch_op.drop_index(batch_op.f('ix_line_reviews_approval_group_id'))

    op.drop_table('line_reviews')
    with op.batch_alter_table('line_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_comments_request_line_id'))

    op.drop_table('line_comments')
    with op.batch_alter_table('line_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_audit_events_request_line_id'))

    op.drop_table('line_audit_events')
    with op.batch_alter_table('request_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_lines_revision_id'))
        batch_op.drop_index(batch_op.f('ix_request_lines_public_line_number'))
        batch_op.drop_index(batch_op.f('ix_request_lines_budget_item_type_id'))

    op.drop_table('request_lines')
    with op.batch_alter_table('draft_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_lines_sort_order'))
        batch_op.drop_index(batch_op.f('ix_draft_lines_draft_id'))
        batch_op.drop_index(batch_op.f('ix_draft_lines_budget_item_type_id'))

    op.drop_table('draft_lines')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_code'))
        batch_op.drop_index(batch_op.f('ix_user_roles_approval_group_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('request_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_drafts_request_id'))

    op.drop_table('request_drafts')
    with op.batch_alter_table('request_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_comments_request_id'))

    op.drop_table('request_comments')
    with op.batch_alter_table('request_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_audit_events_request_id'))

    op.drop_table('request_audit_events')
    with op.batch_alter_table('budget_item_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_item_types_approval_group_id'))

    op.drop_table('budget_item_types')
    op.drop_table('users')
    op.drop_table('requests')
    with op.batch_alter_table('request_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_revisions_request_id'))

    op.drop_table('request_revisions')
    op.drop_table('approval_groups')
    # ### end Alembic commands ###
