"""Add Division model and department association

Revision ID: 831257aa85be
Revises: e433c1e84648
Create Date: 2026-02-18 10:54:54.788519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831257aa85be'
down_revision = 'e433c1e84648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_divisions_code'), ['code'], unique=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_division_id'), ['division_id'], unique=False)
        batch_op.create_foreign_key('fk_departments_division_id', 'divisions', ['division_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_departments_division_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_departments_division_id'))
        batch_op.drop_column('division_id')

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divisions_code'))

    op.drop_table('divisions')
    # ### end Alembic commands ###
