"""Add department and event table

Revision ID: 9af3845e48c6
Revises: 7054f82e599a
Create Date: 2026-01-25 20:07:24.504736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af3845e48c6'
down_revision = '7054f82e599a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mailing_list', sa.String(length=256), nullable=True),
    sa.Column('slack_channel', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('event_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_cycle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requests_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requests_event_cycle_id'), ['event_cycle_id'], unique=False)
        batch_op.create_foreign_key('fk_requests_event_cycle_id', 'event_cycles', ['event_cycle_id'], ['id'])
        batch_op.create_foreign_key('fk_requests_department_id', 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_requests_department_id', type_='foreignkey')
        batch_op.drop_constraint('fk_requests_event_cycle_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requests_event_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_requests_department_id'))
        batch_op.drop_column('department_id')
        batch_op.drop_column('event_cycle_id')

    op.drop_table('event_cycles')
    op.drop_table('departments')
    # ### end Alembic commands ###
