"""Initial schema - portfolio-based workflow engine

Revision ID: 9f9a0ec53783
Revises: 
Create Date: 2026-02-16 20:56:58.425905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9a0ec53783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_groups_code'), ['code'], unique=True)

    op.create_table('confidence_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confidence_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confidence_levels_code'), ['code'], unique=True)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mailing_list', sa.String(length=256), nullable=True),
    sa.Column('slack_channel', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_code'), ['code'], unique=True)

    op.create_table('event_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_cycles_code'), ['code'], unique=True)

    op.create_table('frequency_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('frequency_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_frequency_options_code'), ['code'], unique=True)

    op.create_table('priority_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('priority_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_priority_levels_code'), ['code'], unique=True)

    op.create_table('spend_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spend_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spend_types_code'), ['code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('auth_subject', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_auth_subject'), ['auth_subject'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('work_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_types_code'), ['code'], unique=True)

    op.create_table('department_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('event_cycle_id', sa.Integer(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('is_department_head', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_dept_memberships_department_id'),
    sa.ForeignKeyConstraint(['event_cycle_id'], ['event_cycles.id'], name='fk_dept_memberships_event_cycle_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_dept_memberships_user_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'department_id', 'event_cycle_id', name='uq_dept_membership_user_dept_cycle')
    )
    with op.batch_alter_table('department_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_memberships_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_memberships_event_cycle_id'), ['event_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('expense_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_contract_eligible', sa.Boolean(), nullable=False),
    sa.Column('spend_type_mode', sa.String(length=32), nullable=False),
    sa.Column('default_spend_type_id', sa.Integer(), nullable=True),
    sa.Column('visibility_mode', sa.String(length=32), nullable=False),
    sa.Column('approval_group_id', sa.Integer(), nullable=True),
    sa.Column('is_fixed_cost', sa.Boolean(), nullable=False),
    sa.Column('default_unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('unit_price_locked', sa.Boolean(), nullable=False),
    sa.Column('default_frequency_id', sa.Integer(), nullable=True),
    sa.Column('frequency_locked', sa.Boolean(), nullable=False),
    sa.Column('warehouse_default', sa.Boolean(), nullable=False),
    sa.Column('ui_display_group', sa.String(length=32), nullable=True),
    sa.Column('prompt_mode', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.id'], name='fk_expense_accounts_approval_group_id'),
    sa.ForeignKeyConstraint(['default_frequency_id'], ['frequency_options.id'], name='fk_expense_accounts_default_frequency_id'),
    sa.ForeignKeyConstraint(['default_spend_type_id'], ['spend_types.id'], name='fk_expense_accounts_default_spend_type_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_accounts_approval_group_id'), ['approval_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_expense_accounts_default_frequency_id'), ['default_frequency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_default_spend_type_id'), ['default_spend_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_is_contract_eligible'), ['is_contract_eligible'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_is_fixed_cost'), ['is_fixed_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_prompt_mode'), ['prompt_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_spend_type_mode'), ['spend_type_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_ui_display_group'), ['ui_display_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_accounts_visibility_mode'), ['visibility_mode'], unique=False)

    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role_code', sa.String(length=32), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=True),
    sa.Column('approval_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.id'], name='fk_user_roles_approval_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_roles_user_id'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name='fk_user_roles_work_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_code', 'work_type_id', 'approval_group_id', name='uq_user_role_scoped_once')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_approval_group_id'), ['approval_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_role_code'), ['role_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_work_type_id'), ['work_type_id'], unique=False)

    op.create_table('work_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('event_cycle_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_work_portfolios_department_id'),
    sa.ForeignKeyConstraint(['event_cycle_id'], ['event_cycles.id'], name='fk_work_portfolios_event_cycle_id'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name='fk_work_portfolios_work_type_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_type_id', 'event_cycle_id', 'department_id', name='uq_work_portfolio_type_event_department')
    )
    with op.batch_alter_table('work_portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_portfolios_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_archived_by_user_id'), ['archived_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_event_cycle_id'), ['event_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_portfolios_work_type_id'), ['work_type_id'], unique=False)

    op.create_table('expense_account_departments',
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name='fk_ead_department_id'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['expense_accounts.id'], name='fk_ead_expense_account_id'),
    sa.PrimaryKeyConstraint('expense_account_id', 'department_id')
    )
    op.create_table('expense_account_event_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('event_cycle_id', sa.Integer(), nullable=False),
    sa.Column('is_fixed_cost', sa.Boolean(), nullable=True),
    sa.Column('default_unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('unit_price_locked', sa.Boolean(), nullable=True),
    sa.Column('default_frequency_id', sa.Integer(), nullable=True),
    sa.Column('frequency_locked', sa.Boolean(), nullable=True),
    sa.Column('warehouse_default', sa.Boolean(), nullable=True),
    sa.Column('default_spend_type_id', sa.Integer(), nullable=True),
    sa.Column('ui_display_group', sa.String(length=32), nullable=True),
    sa.Column('prompt_mode', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['default_frequency_id'], ['frequency_options.id'], name='fk_eaeo_default_frequency_id'),
    sa.ForeignKeyConstraint(['default_spend_type_id'], ['spend_types.id'], name='fk_eaeo_default_spend_type_id'),
    sa.ForeignKeyConstraint(['event_cycle_id'], ['event_cycles.id'], name='fk_eaeo_event_cycle_id'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['expense_accounts.id'], name='fk_eaeo_expense_account_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_account_id', 'event_cycle_id', name='uq_eaeo_account_event')
    )
    with op.batch_alter_table('expense_account_event_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_account_event_overrides_default_frequency_id'), ['default_frequency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_account_event_overrides_default_spend_type_id'), ['default_spend_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_account_event_overrides_event_cycle_id'), ['event_cycle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_account_event_overrides_expense_account_id'), ['expense_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_account_event_overrides_prompt_mode'), ['prompt_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_expense_account_event_overrides_ui_display_group'), ['ui_display_group'], unique=False)

    op.create_table('expense_account_spend_types',
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('spend_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['expense_account_id'], ['expense_accounts.id'], name='fk_east_expense_account_id'),
    sa.ForeignKeyConstraint(['spend_type_id'], ['spend_types.id'], name='fk_east_spend_type_id'),
    sa.PrimaryKeyConstraint('expense_account_id', 'spend_type_id')
    )
    op.create_table('work_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('request_kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('review_started_at', sa.DateTime(), nullable=True),
    sa.Column('review_started_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('finalized_note', sa.Text(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('finalized_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('checked_out_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.Column('checked_out_expires_at', sa.DateTime(), nullable=True),
    sa.Column('pending_notification', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('archived_reason', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['work_portfolios.id'], name='fk_work_items_portfolio_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_items_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_archived_by_user_id'), ['archived_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_checked_out_at'), ['checked_out_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_checked_out_by_user_id'), ['checked_out_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_checked_out_expires_at'), ['checked_out_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_finalized_at'), ['finalized_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_finalized_by_user_id'), ['finalized_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index('ix_work_items_portfolio_kind', ['portfolio_id', 'request_kind'], unique=False)
        batch_op.create_index('ix_work_items_portfolio_status', ['portfolio_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_work_items_request_kind'), ['request_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_review_started_at'), ['review_started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_review_started_by_user_id'), ['review_started_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_updated_at'), ['updated_at'], unique=False)

    op.create_table('notification_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template_key', sa.String(length=64), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.String(length=64), nullable=True),
    sa.Column('recipient_email', sa.String(length=256), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name='fk_notification_logs_work_item_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_logs_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_recipient_email'), ['recipient_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_notification_logs_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_template_key'), ['template_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_logs_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('work_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_item_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_amount_cents', sa.Integer(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('status_changed_at', sa.DateTime(), nullable=True),
    sa.Column('status_changed_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('needs_requester_action', sa.Boolean(), nullable=False),
    sa.Column('current_review_stage', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name='fk_work_lines_work_item_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_item_id', 'line_number', name='uq_work_line_number_per_item')
    )
    with op.batch_alter_table('work_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_lines_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_current_review_stage'), ['current_review_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_needs_requester_action'), ['needs_requester_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_status_changed_at'), ['status_changed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_status_changed_by_user_id'), ['status_changed_by_user_id'], unique=False)
        batch_op.create_index('ix_work_lines_status_review_stage', ['status', 'current_review_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_updated_by_user_id'), ['updated_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_lines_work_item_id'), ['work_item_id'], unique=False)

    op.create_table('activity_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.String(length=64), nullable=True),
    sa.Column('work_type_id', sa.Integer(), nullable=True),
    sa.Column('work_item_id', sa.Integer(), nullable=True),
    sa.Column('work_line_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('ip_anon_id', sa.String(length=64), nullable=True),
    sa.Column('ip_net_anon_id', sa.String(length=64), nullable=True),
    sa.Column('ua_anon_id', sa.String(length=64), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('route', sa.String(length=128), nullable=True),
    sa.Column('http_method', sa.String(length=16), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name='fk_activity_events_work_item_id'),
    sa.ForeignKeyConstraint(['work_line_id'], ['work_lines.id'], name='fk_activity_events_work_line_id'),
    sa.ForeignKeyConstraint(['work_type_id'], ['work_types.id'], name='fk_activity_events_work_type_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_ip_anon_id'), ['ip_anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_ip_net_anon_id'), ['ip_net_anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_activity_events_occurred_type', ['occurred_at', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_ua_anon_id'), ['ua_anon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_work_item_id'), ['work_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_work_line_id'), ['work_line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_work_type_id'), ['work_type_id'], unique=False)

    op.create_table('budget_line_details',
    sa.Column('work_line_id', sa.Integer(), nullable=False),
    sa.Column('expense_account_id', sa.Integer(), nullable=False),
    sa.Column('routed_approval_group_id', sa.Integer(), nullable=True),
    sa.Column('spend_type_id', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('confidence_level_id', sa.Integer(), nullable=True),
    sa.Column('frequency_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_flag', sa.Boolean(), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confidence_level_id'], ['confidence_levels.id'], name='fk_budget_line_details_confidence_level_id'),
    sa.ForeignKeyConstraint(['expense_account_id'], ['expense_accounts.id'], name='fk_budget_line_details_expense_account_id'),
    sa.ForeignKeyConstraint(['frequency_id'], ['frequency_options.id'], name='fk_budget_line_details_frequency_id'),
    sa.ForeignKeyConstraint(['priority_id'], ['priority_levels.id'], name='fk_budget_line_details_priority_id'),
    sa.ForeignKeyConstraint(['routed_approval_group_id'], ['approval_groups.id'], name='fk_budget_line_details_routed_approval_group_id'),
    sa.ForeignKeyConstraint(['spend_type_id'], ['spend_types.id'], name='fk_budget_line_details_spend_type_id'),
    sa.ForeignKeyConstraint(['work_line_id'], ['work_lines.id'], name='fk_budget_line_details_work_line_id'),
    sa.PrimaryKeyConstraint('work_line_id')
    )
    with op.batch_alter_table('budget_line_details', schema=None) as batch_op:
        batch_op.create_index('ix_budget_line_details_approval_routing', ['routed_approval_group_id', 'expense_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_confidence_level_id'), ['confidence_level_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_expense_account_id'), ['expense_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_frequency_id'), ['frequency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_priority_id'), ['priority_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_routed_approval_group_id'), ['routed_approval_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_spend_type_id'), ['spend_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_line_details_warehouse_flag'), ['warehouse_flag'], unique=False)

    op.create_table('work_line_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_line_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['work_line_id'], ['work_lines.id'], name='fk_work_line_audit_work_line_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_line_audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_line_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_audit_events_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_audit_events_work_line_id'), ['work_line_id'], unique=False)

    op.create_table('work_line_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_line_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['work_line_id'], ['work_lines.id'], name='fk_work_line_comments_work_line_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_line_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_line_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_comments_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_comments_visibility'), ['visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_comments_work_line_id'), ['work_line_id'], unique=False)

    op.create_table('work_line_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_line_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('approval_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_amount_cents', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approval_group_id'], ['approval_groups.id'], name='fk_work_line_reviews_approval_group_id'),
    sa.ForeignKeyConstraint(['work_line_id'], ['work_lines.id'], name='fk_work_line_reviews_work_line_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_line_id', 'stage', 'approval_group_id', name='uq_work_line_review_per_stage')
    )
    with op.batch_alter_table('work_line_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_line_reviews_approval_group_id'), ['approval_group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_decided_at'), ['decided_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_decided_by_user_id'), ['decided_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_stage'), ['stage'], unique=False)
        batch_op.create_index('ix_work_line_reviews_stage_status', ['stage', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_line_reviews_work_line_id'), ['work_line_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_line_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_work_line_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_updated_at'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_status'))
        batch_op.drop_index('ix_work_line_reviews_stage_status')
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_stage'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_decided_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_decided_at'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_created_at'))
        batch_op.drop_index(batch_op.f('ix_work_line_reviews_approval_group_id'))

    op.drop_table('work_line_reviews')
    with op.batch_alter_table('work_line_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_line_comments_work_line_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_comments_visibility'))
        batch_op.drop_index(batch_op.f('ix_work_line_comments_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_comments_created_at'))

    op.drop_table('work_line_comments')
    with op.batch_alter_table('work_line_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_line_audit_events_work_line_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_work_line_audit_events_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_line_audit_events_created_at'))

    op.drop_table('work_line_audit_events')
    with op.batch_alter_table('budget_line_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_line_details_warehouse_flag'))
        batch_op.drop_index(batch_op.f('ix_budget_line_details_spend_type_id'))
        batch_op.drop_index(batch_op.f('ix_budget_line_details_routed_approval_group_id'))
        batch_op.drop_index(batch_op.f('ix_budget_line_details_priority_id'))
        batch_op.drop_index(batch_op.f('ix_budget_line_details_frequency_id'))
        batch_op.drop_index(batch_op.f('ix_budget_line_details_expense_account_id'))
        batch_op.drop_index(batch_op.f('ix_budget_line_details_confidence_level_id'))
        batch_op.drop_index('ix_budget_line_details_approval_routing')

    op.drop_table('budget_line_details')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_work_type_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_work_line_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_ua_anon_id'))
        batch_op.drop_index('ix_activity_events_occurred_type')
        batch_op.drop_index(batch_op.f('ix_activity_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_activity_events_ip_net_anon_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_ip_anon_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_activity_events_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_actor_user_id'))

    op.drop_table('activity_events')
    with op.batch_alter_table('work_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_lines_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_work_lines_updated_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_lines_updated_at'))
        batch_op.drop_index('ix_work_lines_status_review_stage')
        batch_op.drop_index(batch_op.f('ix_work_lines_status_changed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_lines_status_changed_at'))
        batch_op.drop_index(batch_op.f('ix_work_lines_status'))
        batch_op.drop_index(batch_op.f('ix_work_lines_needs_requester_action'))
        batch_op.drop_index(batch_op.f('ix_work_lines_current_review_stage'))
        batch_op.drop_index(batch_op.f('ix_work_lines_created_at'))

    op.drop_table('work_lines')
    with op.batch_alter_table('notification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_logs_work_item_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_template_key'))
        batch_op.drop_index('ix_notification_logs_status_created')
        batch_op.drop_index(batch_op.f('ix_notification_logs_status'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_sent_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_recipient_email'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_notification_logs_channel'))

    op.drop_table('notification_logs')
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_updated_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_status'))
        batch_op.drop_index(batch_op.f('ix_work_items_review_started_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_review_started_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_request_kind'))
        batch_op.drop_index(batch_op.f('ix_work_items_public_id'))
        batch_op.drop_index('ix_work_items_portfolio_status')
        batch_op.drop_index('ix_work_items_portfolio_kind')
        batch_op.drop_index(batch_op.f('ix_work_items_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_is_archived'))
        batch_op.drop_index(batch_op.f('ix_work_items_finalized_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_finalized_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_created_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_checked_out_expires_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_checked_out_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_checked_out_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_archived_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_archived_at'))

    op.drop_table('work_items')
    op.drop_table('expense_account_spend_types')
    with op.batch_alter_table('expense_account_event_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_account_event_overrides_ui_display_group'))
        batch_op.drop_index(batch_op.f('ix_expense_account_event_overrides_prompt_mode'))
        batch_op.drop_index(batch_op.f('ix_expense_account_event_overrides_expense_account_id'))
        batch_op.drop_index(batch_op.f('ix_expense_account_event_overrides_event_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_expense_account_event_overrides_default_spend_type_id'))
        batch_op.drop_index(batch_op.f('ix_expense_account_event_overrides_default_frequency_id'))

    op.drop_table('expense_account_event_overrides')
    op.drop_table('expense_account_departments')
    with op.batch_alter_table('work_portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_portfolios_work_type_id'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_updated_at'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_is_archived'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_event_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_department_id'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_created_at'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_archived_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_portfolios_archived_at'))

    op.drop_table('work_portfolios')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_work_type_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_code'))
        batch_op.drop_index(batch_op.f('ix_user_roles_approval_group_id'))

    op.drop_table('user_roles')
    with op.batch_alter_table('expense_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_accounts_visibility_mode'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_ui_display_group'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_spend_type_mode'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_prompt_mode'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_is_fixed_cost'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_is_contract_eligible'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_default_spend_type_id'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_default_frequency_id'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_code'))
        batch_op.drop_index(batch_op.f('ix_expense_accounts_approval_group_id'))

    op.drop_table('expense_accounts')
    with op.batch_alter_table('department_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_department_memberships_event_cycle_id'))
        batch_op.drop_index(batch_op.f('ix_department_memberships_department_id'))

    op.drop_table('department_memberships')
    with op.batch_alter_table('work_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_types_code'))

    op.drop_table('work_types')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_auth_subject'))

    op.drop_table('users')
    with op.batch_alter_table('spend_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spend_types_code'))

    op.drop_table('spend_types')
    with op.batch_alter_table('priority_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priority_levels_code'))

    op.drop_table('priority_levels')
    with op.batch_alter_table('frequency_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_frequency_options_code'))

    op.drop_table('frequency_options')
    with op.batch_alter_table('event_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_cycles_code'))

    op.drop_table('event_cycles')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_code'))

    op.drop_table('departments')
    with op.batch_alter_table('confidence_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confidence_levels_code'))

    op.drop_table('confidence_levels')
    with op.batch_alter_table('approval_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_groups_code'))

    op.drop_table('approval_groups')
    # ### end Alembic commands ###
