"""Add snapshot column to work_item_audit_events

Revision ID: caa7a2c1bd85
Revises: h8i9j0k1l2m3
Create Date: 2026-03-02 16:16:43.749450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa7a2c1bd85'
down_revision = 'h8i9j0k1l2m3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('department_membership_work_type_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dmwta_membership_id'))
        batch_op.drop_index(batch_op.f('ix_dmwta_work_type_id'))
        batch_op.create_index(batch_op.f('ix_department_membership_work_type_access_department_membership_id'), ['department_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_membership_work_type_access_work_type_id'), ['work_type_id'], unique=False)

    with op.batch_alter_table('division_membership_work_type_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_divmwta_membership_id'))
        batch_op.drop_index(batch_op.f('ix_divmwta_work_type_id'))
        batch_op.create_index(batch_op.f('ix_division_membership_work_type_access_division_membership_id'), ['division_membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_division_membership_work_type_access_work_type_id'), ['work_type_id'], unique=False)

    with op.batch_alter_table('work_item_audit_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_item_audit_events', schema=None) as batch_op:
        batch_op.drop_column('snapshot')

    with op.batch_alter_table('division_membership_work_type_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_division_membership_work_type_access_work_type_id'))
        batch_op.drop_index(batch_op.f('ix_division_membership_work_type_access_division_membership_id'))
        batch_op.create_index(batch_op.f('ix_divmwta_work_type_id'), ['work_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_divmwta_membership_id'), ['division_membership_id'], unique=False)

    with op.batch_alter_table('department_membership_work_type_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_membership_work_type_access_work_type_id'))
        batch_op.drop_index(batch_op.f('ix_department_membership_work_type_access_department_membership_id'))
        batch_op.create_index(batch_op.f('ix_dmwta_work_type_id'), ['work_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dmwta_membership_id'), ['department_membership_id'], unique=False)

    # ### end Alembic commands ###
