"""Add site_content table

Revision ID: cb686990cd0c
Revises: k1l2m3n4o5p6
Create Date: 2026-03-21 23:49:08.030398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb686990cd0c'
down_revision = 'k1l2m3n4o5p6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('info_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_user_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_content_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_site_content_content_key'), ['content_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_content_content_key'))
        batch_op.drop_index(batch_op.f('ix_site_content_category'))

    op.drop_table('site_content')
    # ### end Alembic commands ###
