"""Add audit columns and ConfigAuditEvent

Revision ID: e136058b082d
Revises: 9f9a0ec53783
Create Date: 2026-02-16 21:25:53.496464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e136058b082d'
down_revision = '9f9a0ec53783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_config_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_audit_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_audit_events_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_audit_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_config_audit_events_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('approval_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('confidence_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('event_cycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('expense_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('frequency_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('priority_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('spend_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_by_user_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spend_types', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('priority_levels', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('frequency_options', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('expense_accounts', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('event_cycles', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('confidence_levels', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('approval_groups', schema=None) as batch_op:
        batch_op.drop_column('updated_by_user_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('description')

    with op.batch_alter_table('config_audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_audit_events_entity_type'))
        batch_op.drop_index(batch_op.f('ix_config_audit_events_entity_id'))
        batch_op.drop_index(batch_op.f('ix_config_audit_events_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_config_audit_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_config_audit_events_action'))
        batch_op.drop_index('ix_config_audit_entity')

    op.drop_table('config_audit_events')
    # ### end Alembic commands ###
