"""Add NEEDS_INFO tracking fields to WorkItem

Revision ID: e433c1e84648
Revises: e136058b082d
Create Date: 2026-02-17 13:40:16.257012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e433c1e84648'
down_revision = 'e136058b082d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_info_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('needs_info_requested_by_user_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_items_needs_info_requested_at'), ['needs_info_requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_needs_info_requested_by_user_id'), ['needs_info_requested_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_needs_info_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_needs_info_requested_at'))
        batch_op.drop_column('needs_info_requested_by_user_id')
        batch_op.drop_column('needs_info_requested_at')

    # ### end Alembic commands ###
