"""Add extension_granted flag to work_items

Revision ID: ext0001flag2
Revises: b9c0d1e2f3a4
Create Date: 2026-05-24

"""
from alembic import op
import sqlalchemy as sa


revision = "ext0001flag2"
down_revision = "b9c0d1e2f3a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_granted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('extension_granted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('extension_granted_by_user_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_items_extension_granted'), ['extension_granted'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_extension_granted_at'), ['extension_granted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_extension_granted_by_user_id'), ['extension_granted_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_extension_granted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_extension_granted_at'))
        batch_op.drop_index(batch_op.f('ix_work_items_extension_granted'))
        batch_op.drop_column('extension_granted_by_user_id')
        batch_op.drop_column('extension_granted_at')
        batch_op.drop_column('extension_granted')

    # ### end Alembic commands ###
