"""Add dispatch tracking fields to WorkItem

Adds dispatched_at and dispatched_by_user_id columns to work_items
for tracking when items are dispatched from the dispatch queue to
the approval queue.

Revision ID: h8i9j0k1l2m3
Revises: g7h8i9j0k1l2
Create Date: 2026-02-25 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h8i9j0k1l2m3'
down_revision = 'g7h8i9j0k1l2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dispatched_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dispatched_by_user_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_work_items_dispatched_at'), ['dispatched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_dispatched_by_user_id'), ['dispatched_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_dispatched_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_items_dispatched_at'))
        batch_op.drop_column('dispatched_by_user_id')
        batch_op.drop_column('dispatched_at')

    # ### end Alembic commands ###
